export const ADD_PLAYER = 'ADD_PLAYER'
export const UPDATE_PLAYER = 'UPDATE_PLAYER'
export const SHOW_PLAYER_BY_JERSEY_NUMBER = 'SHOW_PLAYER_BY_JERSEY_NUMBER'
export const DELETE_PLAYER = 'DELETE_PLAYER'
export const SHOW_ALL_PLAYERS = 'SHOW_ALL_PLAYERS'

// extra 
export const SHOW_PLAYER_BY_NAME = 'SHOW_PLAYER_BY_NAME'
export const SHOW_PLAYER_BY_COUNTRY = 'SHOW_PLAYER_BY_COUNTRY'
export const SHOW_PLAYER_BY_GREATER_RUNS = 'SHOW_PLAYER_BY_GREATER_RUNS'